# action.yml
name: 'xlyk-tagliatelle'
author: 'Kyle Hanks (github.com/xlyk)'
description: 'Utility to update tags and version numbers in config files'
inputs:
  user:
    description: 'github username'
    required: true
  token:
    description: 'github personal access token'
    required: true
  repo:
    description: 'repo that contains target file'
    required: true
  file:
    description: 'target file to update'
    required: true
  tag:
    description: 'string to use as replacement'
    required: true
  pattern:
    description: 'regex pattern to use'
    required: true
  ssh_key:
    description: 'ssh key file'
    required: false
runs:
  using: 'docker'
  image: 'docker://xlyk/tagliatelle:latest'
  args:
    - -repo
    - ${{ inputs.repo }}
    - -file
    - ${{ inputs.file }}
    - -tag
    - ${{ inputs.tag }}
    - -pattern
    - ${{ inputs.pattern }}
    - -ssh-key
    - "${{ inputs.ssh_key }}"
  env:
    GIT_USER: ${{ inputs.user }}
    GIT_TOKEN: ${{ inputs.token }}
